steps:
- name: gcr.io/cloud-builders/git
  args: ['fetch', '--unshallow']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/clash-royale-discord-bot:$SHORT_SHA', '-t', 'gcr.io/$PROJECT_ID/clash-royale-discord-bot:latest', '.']

images: ['gcr.io/$PROJECT_ID/clash-royale-discord-bot']
