version: "3.2"

networks:
  default:
    external:
      name: clashroyalediscord

services:
  redis:
    image: "redis:5.0-rc4-alpine"
    ports:
      - "6379:6379"
    restart: always

  mysql:
    image: "mysql:5.7"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: clash_royale_discord
